export const input = {
	default: {
		container: "input_default-container",
		wrapper: "input_default-wrapper",
		inputWrapper: {
			full: "input_default-full",
			right: "input_default-right",
			left: "input_default-left",
			inside: "input_default-inside",
		},
		label: "input_default-label",
		addonBefore: "input_default-addonBefore",
		addonAfter: "input_default-addonAfter",
		input: "input_default-input",
		prefix: "input_default-prefix",
		sufix: "input_default-sufix",
		hasError: "input_default-hasError",
		description: "input_default-description",
		errorMessage: "error-message",
	},
	inline: {
		container: "input_inline-container",
		wrapper: "input_inline-wrapper",
		inputWrapper: {
			full: "input_inline-full",
			right: "input_inline-right",
			left: "input_inline-left",
			inside: "input_inline-inside",
		},
		label: "input_inline-label",
		addonBefore: "input_inline-addonBefore",
		addonAfter: "input_inline-addonAfter",
		input: "input_inline-input",
		prefix: "input_inline-prefix",
		sufix: "input_inline-sufix",
		hasError: "input_inline-hasError",
		description: "input_inline-description",
		errorMessage: "error-message",
	},
	overlay: {
		container: "input_overlay-container",
		wrapper: "input_overlay-wrapper",
		inputWrapper: {
			full: "input_overlay-full",
			right: "input_overlay-right",
			left: "input_overlay-left",
			inside: "input_overlay-inside",
		},
		label: "input_overlay-label",
		addonBefore: "input_overlay-addonBefore",
		addonAfter: "input_overlay-addonAfter",
		input: "input_overlay-input",
		prefix: "input_overlay-prefix",
		sufix: "input_overlay-sufix",
		hasError: "input_overlay-hasError",
		description: "input_overlay-description",
		errorMessage: "error-message",
	},
	search: {
		container: "input_search-container",
		wrapper: "input_search-wrapper",
		inputWrapper: {
			full: "input_search-full",
			right: "input_search-right",
			left: "input_search-left",
			inside: "input_search-inside",
		},
		label: "input_search-label",
		addonBefore: "input_search-addonBefore",
		addonAfter: "input_search-addonAfter",
		input: "input_search-input",
		prefix: "input_search-prefix",
		sufix: "input_search-sufix",
		hasError: "input_search-hasError",
		description: "input_search-description",
		errorMessage: "error-message",
	},
}
